# conf/model/lstm_ae.yaml

lstm_ae:
  seed: ${seed}

  hidden_dim: 64
  latent_dim: 16
  num_layers: 2
  dropout: 0.1

  window_size: 30
  window_stride: 1

  batch_size: 128
  num_epochs: 20
  lr: 0.001
  weight_decay: 1e-5
  clip_grad_norm: 1.0

  device: null
  threshold_quantile: 0.995
  print_progress: true

  run_score_quantile: 0.99
  run_threshold_quantile: 0.995
